import type { Student, StudentProfile, TeacherProfile } from "./types";

export const teacher: TeacherProfile = {
  id: "usr-sri-wahyuni",
  email: "sri.wahyuni@slb1yogya.sch.id",
  fullName: "Sri Wahyuni, S.Pd.",
  nickname: "Bu Wahyuni",
  role: "teacher",
  schoolName: "SLB Negeri 1 Yogyakarta",
  city: "Yogyakarta",
  subjects: ["Matematika", "IPA", "Bahasa Indonesia"],
  photoUrl: "https://picsum.photos/seed/fitra-guru-sri-wahyuni/240/240",
  onboardingCompleted: true,
  preferences: { notificationsEnabled: true },
};

export const students: Student[] = [
  {
    id: "stu-aisyah",
    teacherId: teacher.id,
    fullName: "Aisyah Putri Ramadhani",
    nickname: "Aisyah",
    age: 9,
    gender: "P",
    photoUrl: "https://picsum.photos/seed/fitra-aisyah-putri/240/240",
    disabilityType: "tunarungu",
    notes:
      "Hafal kosakata materi dengan cepat. Membaca soal cerita masih sulit. Tangan kanan dominan untuk finger agung.",
    createdAt: "2025-08-12",
  },
  {
    id: "stu-bagas",
    teacherId: teacher.id,
    fullName: "Bagas Santoso",
    nickname: "Bagas",
    age: 10,
    gender: "L",
    photoUrl: "https://picsum.photos/seed/fitra-bagas-santoso/240/240",
    disabilityType: "tunagrahita",
    notes:
      "Teliti pada tugas konkret bergambar. Mengenal angka 1 sampai 20 sudah dikuasai. Butuh waktu lama untuk membaca teks panjang.",
    createdAt: "2025-08-14",
  },
  {
    id: "stu-citra",
    teacherId: teacher.id,
    fullName: "Citra Ayu Lestari",
    nickname: "Citra",
    age: 8,
    gender: "P",
    photoUrl: "https://picsum.photos/seed/fitra-citra-ayu/240/240",
    disabilityType: "tunanetra",
    notes:
      "Semua materi harus berbahasa audio. Setiap gambar wajib disertai deskripsi lengkap. Terbiasa memakai screen reader di kelas.",
    createdAt: "2025-08-18",
  },
  {
    id: "stu-dimas",
    teacherId: teacher.id,
    fullName: "Dimas Prasetyo",
    nickname: "Dimas",
    age: 11,
    gender: "L",
    photoUrl: "https://picsum.photos/seed/fitra-dimas-prasetyo/240/240",
    disabilityType: "tunadaksa",
    notes:
      "Berjalan dengan kursi roda. Genggaman tangan kanan terbatas, jadi semua jawaban memakai pilihan sentuh besar, bukan drag.",
    createdAt: "2025-08-20",
  },
  {
    id: "stu-eka",
    teacherId: teacher.id,
    fullName: "Eka Nurhaliza",
    nickname: "Eka",
    age: 9,
    gender: "P",
    photoUrl: "https://picsum.photos/seed/fitra-eka-nurhaliza/240/240",
    disabilityType: "autis",
    notes:
      "Suka rutinitas yang jelas. Beri tahu lebih awal jika urutan kegiatan berubah. Suara di belakang dapat membuat Eka menutup telinga.",
    createdAt: "2025-08-25",
  },
  {
    id: "stu-fajar",
    teacherId: teacher.id,
    fullName: "Fajar Nugroho",
    nickname: "Fajar",
    age: 10,
    gender: "L",
    photoUrl: "https://picsum.photos/seed/fitra-fajar-nugroho/240/240",
    disabilityType: "tunawicara",
    notes:
      "Berkomunikasi dengan papan komunikasi dan gestur. Merespons optimal dengan instruksi lisan sambil menunjuk benda.",
    createdAt: "2025-09-01",
  },
  {
    id: "stu-rizky",
    teacherId: teacher.id,
    fullName: "Rizky Ramadhan",
    nickname: "Rizky",
    age: 8,
    gender: "L",
    photoUrl: "https://picsum.photos/seed/fitra-rizky-ramadhan/240/240",
    disabilityType: "tunaganda",
    notes:
      "Gangguan pendengaran. Instruksi diberikan dengan wajah menghadap siswa dan gerak bibir yang jelas. Kemampuan membaca huruf besar sudah berkembang bulan ini.",
    createdAt: "2025-09-04",
  },
  {
    id: "stu-sinta",
    teacherId: teacher.id,
    fullName: "Sinta Wulandari",
    nickname: "Sinta",
    age: 9,
    gender: "P",
    photoUrl: "https://picsum.photos/seed/fitra-sinta-wulandari/240/240",
    disabilityType: "tunalaras",
    notes:
      "Paling cepat membaca di kelas. Mudah teralihkan bila tugas berubah, jadi aktivitas selalu dipecah tiga bagian pendek.",
    createdAt: "2025-09-08",
  },
];

export const studentProfiles: StudentProfile[] = [
  {
    studentId: "stu-aisyah",
    academicLevel: "medium",
    academicDetails: { membaca: "medium", menulis: "medium", berhitung: "low" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "medium",
      mengaturEmosi: "medium",
      catatan:
        "Aisyah berani tampil di depan kelas, tetapi tidak suka kalau jawabannya dibantah di depan orang.",
    },
    motorSkills: {
      motorHalus: "high",
      motorKasar: "medium",
      catatan: "Jari telunjuk kuat untuk gestur dua kata dalam Bahasa isyarat.",
    },
    independence: {
      dressed: "high",
      makan: "high",
      menggunakanAlat: "medium",
      catatan: "Mampu menyiapkan alat belajar sendiri jika langkahnya ditulis singkat.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: false },
    interactionModes: { touch: true, speech: true, keyboard: false, switch: false, drag: true },
    uiTokens: {
      fontSize: "medium",
      contrastMode: "normal",
      audioEnabled: true,
      audioSpeed: "normal",
      navStyle: "step",
    },
    updatedAt: "2026-02-18",
  },
  {
    studentId: "stu-bagas",
    academicLevel: "low",
    academicDetails: { membaca: "low", menulis: "low", berhitung: "medium" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "high",
      mengaturEmosi: "medium",
      catatan: "Rajin dan tekun. Sering meminta izin mengerjakan dua kali karena ingin memastikan.",
    },
    motorSkills: {
      motorHalus: "medium",
      motorKasar: "high",
      catatan: "Kuat pada puzzle fisik dan memindahkan benda konkret.",
    },
    independence: {
      dressed: "high",
      makan: "high",
      menggunakanAlat: "low",
      catatan: "Perlu instruksi singkat yang diulang dua kali sebelum mulai tugas.",
    },
    learningPreferences: { visual: true, audio: false, kinestetik: true },
    interactionModes: { touch: true, speech: false, keyboard: false, switch: true, drag: true },
    uiTokens: {
      fontSize: "high",
      contrastMode: "high",
      audioEnabled: false,
      audioSpeed: "slow",
      navStyle: "step",
    },
    updatedAt: "2026-02-20",
  },
  {
    studentId: "stu-citra",
    academicLevel: "medium",
    academicDetails: { membaca: "medium", menulis: "medium", berhitung: "medium" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "medium",
      mengaturEmosi: "high",
      catatan: "Mandiri saat mengerjakan. Meminta bantuan hanya ketika deskripsi gambar kurang jelas.",
    },
    motorSkills: {
      motorHalus: "medium",
      motorKasar: "medium",
      catatan: "Menyentuh bahan braille dengan telunjuk kiri.",
    },
    independence: {
      dressed: "high",
      makan: "high",
      menggunakanAlat: "high",
      catatan: "Sangat mandiri, tidak memerlukan pendampingan untuk menyiapkan alat.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: false },
    interactionModes: { touch: true, speech: true, keyboard: false, switch: false, drag: false },
    uiTokens: {
      fontSize: "medium",
      contrastMode: "high",
      audioEnabled: true,
      audioSpeed: "slow",
      navStyle: "scroll",
    },
    updatedAt: "2026-02-21",
  },
  {
    studentId: "stu-dimas",
    academicLevel: "medium",
    academicDetails: { membaca: "medium", menulis: "low", berhitung: "medium" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "high",
      mengaturEmosi: "medium",
      catatan: "Inisiatif tinggi, suka memimpin permainan di kelas.",
    },
    motorSkills: {
      motorHalus: "low",
      motorKasar: "low",
      catatan:
      "Genggaman tangan kanan terbatas karena cedera saat latihan. Semua interaksi memakai pilihan sentuh besar, bukan drag.",
    },
    independence: {
      dressed: "medium",
      makan: "medium",
      menggunakanAlat: "medium",
      catatan: "Perlu waktu tambahan 15 menit untuk menyusun lembar kerja.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: false },
    interactionModes: { touch: true, speech: true, keyboard: false, switch: true, drag: false },
    uiTokens: {
      fontSize: "medium",
      contrastMode: "normal",
      audioEnabled: true,
      audioSpeed: "normal",
      navStyle: "tap",
    },
    updatedAt: "2026-02-22",
  },
  {
    studentId: "stu-eka",
    academicLevel: "medium",
    academicDetails: { membaca: "medium", menulis: "low", berhitung: "medium" },
    socialEmotional: {
      mengenaliOrang: "medium",
      bekerjaSama: "low",
      mengaturEmosi: "low",
      catatan:
        "Menangis bila kegiatan berubah mendadak. Tenang jika tahu urutan kegiatan sejak pagi.",
    },
    motorSkills: {
      motorHalus: "high",
      motorKasar: "medium",
      catatan: "Telaten pada kartu bergambar. Urutan kartu tidak boleh diubah.",
    },
    independence: {
      dressed: "medium",
      makan: "medium",
      menggunakanAlat: "medium",
      catatan: "Memerlukan daftar periksa bergambar sebelum memulai kegiatan.",
    },
    learningPreferences: { visual: true, audio: false, kinestetik: true },
    interactionModes: { touch: true, speech: false, keyboard: false, switch: true, drag: false },
    uiTokens: {
      fontSize: "medium",
      contrastMode: "normal",
      audioEnabled: false,
      audioSpeed: "slow",
      navStyle: "step",
    },
    updatedAt: "2026-02-23",
  },
  {
    studentId: "stu-fajar",
    academicLevel: "low",
    academicDetails: { membaca: "low", menulis: "low", berhitung: "low" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "medium",
      mengaturEmosi: "medium",
      catatan:
        "Merespons dengan papan komunikasi dua dan tiga kata. Instruksi selalu lisan sambil menunjuk benda.",
    },
    motorSkills: {
      motorHalus: "medium",
      motorKasar: "high",
      catatan: "Bisa bertepuk tangan sendiri sebagai bentuk konsekuensi yang baik.",
    },
    independence: {
      dressed: "low",
      makan: "medium",
      menggunakanAlat: "low",
      catatan: "Membutuhkan papan komunikasi di dalam kelas dan pendampingan fisik saat memakai alat.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: true },
    interactionModes: { touch: true, speech: false, keyboard: false, switch: true, drag: false },
    uiTokens: {
      fontSize: "high",
      contrastMode: "high",
      audioEnabled: true,
      audioSpeed: "slow",
      navStyle: "tap",
    },
    updatedAt: "2026-02-24",
  },
  {
    studentId: "stu-rizky",
    academicLevel: "low",
    academicDetails: { membaca: "low", menulis: "low", berhitung: "low" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "medium",
      mengaturEmosi: "medium",
      catatan: "Sangat disiplin mengikuti instruksi. Di kelas sering berbicara dengan suara keras tanpa diminta.",
    },
    motorSkills: {
      motorHalus: "medium",
      motorKasar: "medium",
      catatan: "Mampu bertahan dalam tugas terstruktur selama 5 menit sebelum perlu istirahat.",
    },
    independence: {
      dressed: "medium",
      makan: "low",
      menggunakanAlat: "low",
      catatan: "Semua perpindahan kegiatan diberi aba-aba verbal dan visual.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: false },
    interactionModes: { touch: true, speech: false, keyboard: false, switch: true, drag: false },
    uiTokens: {
      fontSize: "high",
      contrastMode: "normal",
      audioEnabled: true,
      audioSpeed: "normal",
      navStyle: "tap",
    },
    updatedAt: "2026-02-25",
  },
  {
    studentId: "stu-sinta",
    academicLevel: "high",
    academicDetails: { membaca: "high", menulis: "high", berhitung: "medium" },
    socialEmotional: {
      mengenaliOrang: "high",
      bekerjaSama: "high",
      mengaturEmosi: "low",
      catatan:
        "Paling cepat membaca di kelas. Mudah teralihkan bila tugas berubah, jadi aktivitas selalu dipecah tiga bagian pendek.",
    },
    motorSkills: {
      motorHalus: "high",
      motorKasar: "high",
      catatan: "Kuat di semua kegiatan motorik, termasuk memotong dan menempel.",
    },
    independence: {
      dressed: "high",
      makan: "high",
      menggunakanAlat: "high",
      catatan: "Tidak memerlukan pendampingan saat menyiapkan alat belajar.",
    },
    learningPreferences: { visual: true, audio: true, kinestetik: true },
    interactionModes: { touch: true, speech: true, keyboard: true, switch: false, drag: true },
    uiTokens: {
      fontSize: "low",
      contrastMode: "normal",
      audioEnabled: true,
      audioSpeed: "fast",
      navStyle: "step",
    },
    updatedAt: "2026-02-26",
  },
];
